-- Initial schema for INTEX dataset (17 CSV tables)
-- Applied automatically by `supabase start` / `supabase db reset`.

begin;

-- Donor & Support domain
create table if not exists public.safehouses (
  safehouse_id integer generated by default as identity primary key,
  safehouse_code text,
  name text,
  region text,
  city text,
  province text,
  country text,
  open_date date,
  status text,
  capacity_girls integer,
  capacity_staff integer,
  current_occupancy integer,
  notes text
);

create table if not exists public.partners (
  partner_id integer generated by default as identity primary key,
  partner_name text,
  partner_type text,
  role_type text,
  contact_name text,
  email text,
  phone text,
  region text,
  status text,
  start_date date,
  end_date date,
  notes text
);

create table if not exists public.partner_assignments (
  assignment_id integer generated by default as identity primary key,
  partner_id integer not null references public.partners(partner_id) on delete restrict,
  safehouse_id integer references public.safehouses(safehouse_id) on delete restrict,
  program_area text,
  assignment_start date,
  assignment_end date,
  responsibility_notes text,
  is_primary boolean,
  status text
);
create index if not exists partner_assignments_partner_id_idx on public.partner_assignments(partner_id);
create index if not exists partner_assignments_safehouse_id_idx on public.partner_assignments(safehouse_id);

create table if not exists public.supporters (
  supporter_id integer generated by default as identity primary key,
  supporter_type text,
  display_name text,
  organization_name text,
  first_name text,
  last_name text,
  relationship_type text,
  region text,
  country text,
  email text,
  phone text,
  status text,
  first_donation_date date,
  acquisition_channel text,
  created_at timestamptz
);

create table if not exists public.social_media_posts (
  post_id integer generated by default as identity primary key,
  platform text,
  platform_post_id text,
  post_url text,
  created_at timestamptz,
  day_of_week text,
  post_hour integer,
  post_type text,
  media_type text,
  caption text,
  hashtags text,
  num_hashtags integer,
  mentions_count integer,
  has_call_to_action boolean,
  call_to_action_type text,
  content_topic text,
  sentiment_tone text,
  caption_length integer,
  features_resident_story boolean,
  campaign_name text,
  is_boosted boolean,
  boost_budget_php numeric,
  impressions integer,
  reach integer,
  likes integer,
  comments integer,
  shares integer,
  saves integer,
  click_throughs integer,
  video_views integer,
  engagement_rate numeric,
  profile_visits integer,
  donation_referrals integer,
  estimated_donation_value_php numeric,
  follower_count_at_post integer,
  watch_time_seconds integer,
  avg_view_duration_seconds integer,
  subscriber_count_at_post integer,
  forwards integer
);

create table if not exists public.donations (
  donation_id integer generated by default as identity primary key,
  supporter_id integer references public.supporters(supporter_id) on delete set null,
  donation_type text,
  donation_date date,
  channel_source text,
  currency_code text,
  amount numeric,
  estimated_value numeric,
  impact_unit text,
  is_recurring boolean,
  campaign_name text,
  notes text,
  created_by_partner_id integer references public.partners(partner_id) on delete set null,
  referral_post_id integer references public.social_media_posts(post_id) on delete set null
);
create index if not exists donations_supporter_id_idx on public.donations(supporter_id);
create index if not exists donations_referral_post_id_idx on public.donations(referral_post_id);

create table if not exists public.donation_allocations (
  allocation_id integer generated by default as identity primary key,
  donation_id integer not null references public.donations(donation_id) on delete cascade,
  safehouse_id integer references public.safehouses(safehouse_id) on delete restrict,
  program_area text,
  amount_allocated numeric,
  allocation_date date,
  allocation_notes text
);
create index if not exists donation_allocations_donation_id_idx on public.donation_allocations(donation_id);
create index if not exists donation_allocations_safehouse_id_idx on public.donation_allocations(safehouse_id);

create table if not exists public.in_kind_donation_items (
  item_id integer generated by default as identity primary key,
  donation_id integer not null references public.donations(donation_id) on delete cascade,
  item_name text,
  item_category text,
  quantity integer,
  unit_of_measure text,
  estimated_unit_value numeric,
  intended_use text,
  received_condition text
);
create index if not exists in_kind_donation_items_donation_id_idx on public.in_kind_donation_items(donation_id);

-- Case Management domain
create table if not exists public.residents (
  resident_id integer generated by default as identity primary key,
  case_control_no text,
  internal_code text,
  safehouse_id integer references public.safehouses(safehouse_id) on delete set null,
  case_status text,
  sex text,
  date_of_birth date,
  birth_status text,
  place_of_birth text,
  religion text,
  case_category text,
  sub_cat_orphaned boolean,
  sub_cat_trafficked boolean,
  sub_cat_child_labor boolean,
  sub_cat_physical_abuse boolean,
  sub_cat_sexual_abuse boolean,
  sub_cat_osaec boolean,
  sub_cat_cicl boolean,
  sub_cat_at_risk boolean,
  sub_cat_street_child boolean,
  sub_cat_child_with_hiv boolean,
  is_pwd boolean,
  pwd_type text,
  has_special_needs boolean,
  special_needs_diagnosis text,
  family_is_4ps boolean,
  family_solo_parent boolean,
  family_indigenous boolean,
  family_parent_pwd boolean,
  family_informal_settler boolean,
  date_of_admission date,
  age_upon_admission text,
  present_age text,
  length_of_stay text,
  referral_source text,
  referring_agency_person text,
  date_colb_registered date,
  date_colb_obtained date,
  assigned_social_worker text,
  initial_case_assessment text,
  date_case_study_prepared date,
  reintegration_type text,
  reintegration_status text,
  initial_risk_level text,
  current_risk_level text,
  date_enrolled date,
  date_closed date,
  created_at timestamptz,
  notes_restricted text
);
create index if not exists residents_safehouse_id_idx on public.residents(safehouse_id);

create table if not exists public.process_recordings (
  recording_id integer generated by default as identity primary key,
  resident_id integer not null references public.residents(resident_id) on delete cascade,
  session_date date,
  social_worker text,
  session_type text,
  session_duration_minutes integer,
  emotional_state_observed text,
  emotional_state_end text,
  session_narrative text,
  interventions_applied text,
  follow_up_actions text,
  progress_noted boolean,
  concerns_flagged boolean,
  referral_made boolean,
  notes_restricted text
);
create index if not exists process_recordings_resident_id_idx on public.process_recordings(resident_id);

create table if not exists public.home_visitations (
  visitation_id integer generated by default as identity primary key,
  resident_id integer not null references public.residents(resident_id) on delete cascade,
  visit_date date,
  social_worker text,
  visit_type text,
  location_visited text,
  family_members_present text,
  purpose text,
  observations text,
  family_cooperation_level text,
  safety_concerns_noted boolean,
  follow_up_needed boolean,
  follow_up_notes text,
  visit_outcome text
);
create index if not exists home_visitations_resident_id_idx on public.home_visitations(resident_id);

create table if not exists public.education_records (
  education_record_id integer generated by default as identity primary key,
  resident_id integer not null references public.residents(resident_id) on delete cascade,
  record_date date,
  program_name text,
  course_name text,
  education_level text,
  attendance_status text,
  attendance_rate numeric,
  progress_percent numeric,
  completion_status text,
  gpa_like_score numeric,
  notes text
);
create index if not exists education_records_resident_id_idx on public.education_records(resident_id);

create table if not exists public.health_wellbeing_records (
  health_record_id integer generated by default as identity primary key,
  resident_id integer not null references public.residents(resident_id) on delete cascade,
  record_date date,
  weight_kg numeric,
  height_cm numeric,
  bmi numeric,
  nutrition_score numeric,
  sleep_score numeric,
  energy_score numeric,
  general_health_score numeric,
  medical_checkup_done boolean,
  dental_checkup_done boolean,
  psychological_checkup_done boolean,
  medical_notes_restricted text
);
create index if not exists health_wellbeing_records_resident_id_idx on public.health_wellbeing_records(resident_id);

create table if not exists public.intervention_plans (
  plan_id integer generated by default as identity primary key,
  resident_id integer not null references public.residents(resident_id) on delete cascade,
  plan_category text,
  plan_description text,
  services_provided text,
  target_value numeric,
  target_date date,
  status text,
  case_conference_date date,
  created_at timestamptz,
  updated_at timestamptz
);
create index if not exists intervention_plans_resident_id_idx on public.intervention_plans(resident_id);

create table if not exists public.incident_reports (
  incident_id integer generated by default as identity primary key,
  resident_id integer references public.residents(resident_id) on delete set null,
  safehouse_id integer references public.safehouses(safehouse_id) on delete set null,
  incident_date date,
  incident_type text,
  severity text,
  description text,
  response_taken text,
  resolved boolean,
  resolution_date date,
  reported_by text,
  follow_up_required boolean
);
create index if not exists incident_reports_resident_id_idx on public.incident_reports(resident_id);
create index if not exists incident_reports_safehouse_id_idx on public.incident_reports(safehouse_id);

create table if not exists public.safehouse_monthly_metrics (
  metric_id integer generated by default as identity primary key,
  safehouse_id integer not null references public.safehouses(safehouse_id) on delete cascade,
  month_start date,
  month_end date,
  active_residents integer,
  avg_education_progress numeric,
  avg_health_score numeric,
  process_recording_count integer,
  home_visitation_count integer,
  incident_count integer,
  notes text
);
create index if not exists safehouse_monthly_metrics_safehouse_id_idx on public.safehouse_monthly_metrics(safehouse_id);

-- Outreach domain
create table if not exists public.public_impact_snapshots (
  snapshot_id integer generated by default as identity primary key,
  snapshot_date date,
  headline text,
  summary_text text,
  metric_payload_json text,
  is_published boolean,
  published_at date
);

commit;

